insert into Localisation (nom_lieu) values ('Bunting');
insert into Localisation (nom_lieu) values ('Scoville');
insert into Localisation (nom_lieu) values ('Namekagon');
insert into Localisation (nom_lieu) values ('Northridge');
insert into Localisation (nom_lieu) values ('Michigan');
insert into Localisation (nom_lieu) values ('Grayhawk');
insert into Localisation (nom_lieu) values ('Granby');
insert into Localisation (nom_lieu) values ('Waxwing');
insert into Localisation (nom_lieu) values ('American');
insert into Localisation (nom_lieu) values ('Londonderry');
insert into Localisation (nom_lieu) values ('Badeau');
insert into Localisation (nom_lieu) values ('Gerald');
insert into Localisation (nom_lieu) values ('Thompson');
insert into Localisation (nom_lieu) values ('Thierer');
insert into Localisation (nom_lieu) values ('Michigan');
insert into Localisation (nom_lieu) values ('Hovde');
insert into Localisation (nom_lieu) values ('Gateway');
insert into Localisation (nom_lieu) values ('Little Fleur');
insert into Localisation (nom_lieu) values ('Straubel');
insert into Localisation (nom_lieu) values ('Memorial');
insert into Localisation (nom_lieu) values ('Laurel');
insert into Localisation (nom_lieu) values ('Messerschmidt');
insert into Localisation (nom_lieu) values ('Karstens');
insert into Localisation (nom_lieu) values ('Pawling');
insert into Localisation (nom_lieu) values ('Continental');
insert into Localisation (nom_lieu) values ('Bunker Hill');
insert into Localisation (nom_lieu) values ('Towne');
insert into Localisation (nom_lieu) values ('Elgar');
insert into Localisation (nom_lieu) values ('Grim');
insert into Localisation (nom_lieu) values ('7th');
insert into Localisation (nom_lieu) values ('Heath');
insert into Localisation (nom_lieu) values ('Doe Crossing');
insert into Localisation (nom_lieu) values ('Elka');
insert into Localisation (nom_lieu) values ('Longview');
insert into Localisation (nom_lieu) values ('Valley Edge');
insert into Localisation (nom_lieu) values ('Sunbrook');
insert into Localisation (nom_lieu) values ('Porter');
insert into Localisation (nom_lieu) values ('Drewry');
insert into Localisation (nom_lieu) values ('Becker');
insert into Localisation (nom_lieu) values ('Coleman');
insert into Localisation (nom_lieu) values ('Sachs');
insert into Localisation (nom_lieu) values ('Mitchell');
insert into Localisation (nom_lieu) values ('Bluestem');
insert into Localisation (nom_lieu) values ('Bluejay');
insert into Localisation (nom_lieu) values ('Algoma');
insert into Localisation (nom_lieu) values ('Armistice');
insert into Localisation (nom_lieu) values ('Village Green');
insert into Localisation (nom_lieu) values ('Mendota');
insert into Localisation (nom_lieu) values ('Farwell');
insert into Localisation (nom_lieu) values ('Lakewood Gardens');
insert into Localisation (nom_lieu) values ('Judy');
insert into Localisation (nom_lieu) values ('Swallow');
insert into Localisation (nom_lieu) values ('Algoma');
insert into Localisation (nom_lieu) values ('Brickson Park');
insert into Localisation (nom_lieu) values ('Merrick');
insert into Localisation (nom_lieu) values ('Express');
insert into Localisation (nom_lieu) values ('Goodland');
insert into Localisation (nom_lieu) values ('Dovetail');
insert into Localisation (nom_lieu) values ('Rigney');
insert into Localisation (nom_lieu) values ('Mandrake');
insert into Localisation (nom_lieu) values ('Towne');
insert into Localisation (nom_lieu) values ('Lighthouse Bay');
insert into Localisation (nom_lieu) values ('Stuart');
insert into Localisation (nom_lieu) values ('Glacier Hill');
insert into Localisation (nom_lieu) values ('Meadow Ridge');
insert into Localisation (nom_lieu) values ('Meadow Valley');
insert into Localisation (nom_lieu) values ('Brown');
insert into Localisation (nom_lieu) values ('Hanover');
insert into Localisation (nom_lieu) values ('Packers');
insert into Localisation (nom_lieu) values ('Warrior');
insert into Localisation (nom_lieu) values ('North');
insert into Localisation (nom_lieu) values ('Pennsylvania');
insert into Localisation (nom_lieu) values ('Granby');
insert into Localisation (nom_lieu) values ('Pleasure');
insert into Localisation (nom_lieu) values ('Monica');
insert into Localisation (nom_lieu) values ('Delladonna');
insert into Localisation (nom_lieu) values ('Briar Crest');
insert into Localisation (nom_lieu) values ('Manitowish');
insert into Localisation (nom_lieu) values ('Kings');
insert into Localisation (nom_lieu) values ('Northridge');
insert into Localisation (nom_lieu) values ('Chinook');
insert into Localisation (nom_lieu) values ('Mayer');
insert into Localisation (nom_lieu) values ('Di Loreto');
insert into Localisation (nom_lieu) values ('Colorado');
insert into Localisation (nom_lieu) values ('Moland');
insert into Localisation (nom_lieu) values ('Elgar');
insert into Localisation (nom_lieu) values ('Myrtle');
insert into Localisation (nom_lieu) values ('Scofield');
insert into Localisation (nom_lieu) values ('Larry');
insert into Localisation (nom_lieu) values ('Mendota');
insert into Localisation (nom_lieu) values ('School');
insert into Localisation (nom_lieu) values ('Service');
insert into Localisation (nom_lieu) values ('Stuart');
insert into Localisation (nom_lieu) values ('Lerdahl');
insert into Localisation (nom_lieu) values ('Towne');
insert into Localisation (nom_lieu) values ('Sundown');
insert into Localisation (nom_lieu) values ('Corben');
insert into Localisation (nom_lieu) values ('Kings');
insert into Localisation (nom_lieu) values ('Homewood');
insert into Localisation (nom_lieu) values ('Knutson');
