insert into Tag (nom_tag) values ('donec ut dolor');
insert into Tag (nom_tag) values ('consequat nulla nisl');
insert into Tag (nom_tag) values ('dictumst');
insert into Tag (nom_tag) values ('eu');
insert into Tag (nom_tag) values ('aenean sit');
insert into Tag (nom_tag) values ('nisl aenean lectus');
insert into Tag (nom_tag) values ('in lacus curabitur');
insert into Tag (nom_tag) values ('ac');
insert into Tag (nom_tag) values ('turpis');
insert into Tag (nom_tag) values ('tellus semper interdum');
insert into Tag (nom_tag) values ('in lacus');
insert into Tag (nom_tag) values ('viverra pede ac');
insert into Tag (nom_tag) values ('id mauris vulputate');
insert into Tag (nom_tag) values ('ut tellus nulla');
insert into Tag (nom_tag) values ('ipsum primis');
insert into Tag (nom_tag) values ('turpis');
insert into Tag (nom_tag) values ('luctus');
insert into Tag (nom_tag) values ('eget');
insert into Tag (nom_tag) values ('eu mi');
insert into Tag (nom_tag) values ('at velit');
insert into Tag (nom_tag) values ('nam congue');
insert into Tag (nom_tag) values ('libero quis');
insert into Tag (nom_tag) values ('id lobortis convallis');
insert into Tag (nom_tag) values ('pretium iaculis justo');
insert into Tag (nom_tag) values ('nulla nisl nunc');
insert into Tag (nom_tag) values ('neque aenean auctor');
insert into Tag (nom_tag) values ('sed nisl nunc');
insert into Tag (nom_tag) values ('non velit');
insert into Tag (nom_tag) values ('quam nec');
insert into Tag (nom_tag) values ('metus');
insert into Tag (nom_tag) values ('erat');
insert into Tag (nom_tag) values ('posuere cubilia curae');
insert into Tag (nom_tag) values ('elit proin');
insert into Tag (nom_tag) values ('id');
insert into Tag (nom_tag) values ('mattis');
insert into Tag (nom_tag) values ('cras');
insert into Tag (nom_tag) values ('sociis natoque');
insert into Tag (nom_tag) values ('sapien ut');
insert into Tag (nom_tag) values ('leo');
insert into Tag (nom_tag) values ('non');
insert into Tag (nom_tag) values ('tempus');
insert into Tag (nom_tag) values ('luctus cum sociis');
insert into Tag (nom_tag) values ('curabitur');
insert into Tag (nom_tag) values ('tellus nulla ut');
insert into Tag (nom_tag) values ('enim lorem');
insert into Tag (nom_tag) values ('lorem quisque ut');
insert into Tag (nom_tag) values ('mus vivamus vestibulum');
insert into Tag (nom_tag) values ('duis aliquam convallis');
insert into Tag (nom_tag) values ('orci nullam molestie');
insert into Tag (nom_tag) values ('vulputate');
