INSERT INTO Localisation(nom_lieu) values ('Alarobia Vatosola');
INSERT INTO Localisation(nom_lieu) values ('Alatsinainy Bakaro');
INSERT INTO Localisation(nom_lieu) values ('Ambohimiadana');
INSERT INTO Localisation(nom_lieu) values ('Andohariana');
INSERT INTO Localisation(nom_lieu) values ('Andramasina');
INSERT INTO Localisation(nom_lieu) values ('Anosibe Trimoloharano');
INSERT INTO Localisation(nom_lieu) values ('Antotohazo');
INSERT INTO Localisation(nom_lieu) values ('Fitsinjovana Bakaro');
INSERT INTO Localisation(nom_lieu) values ('Mandrosoa');
INSERT INTO Localisation(nom_lieu) values ('Sabotsy Ambohitromby');
INSERT INTO Localisation(nom_lieu) values ('Sabotsy Manjakavahoaka');
INSERT INTO Localisation(nom_lieu) values ('Tankafatra');
INSERT INTO Localisation(nom_lieu) values ('Ambato');
INSERT INTO Localisation(nom_lieu) values ('Ambatolampy Tsimahafotsy');
INSERT INTO Localisation(nom_lieu) values ('Ambohidratrimo');
INSERT INTO Localisation(nom_lieu) values ('Ambohimanjaka');
INSERT INTO Localisation(nom_lieu) values ('Ambohimpihaonana');
INSERT INTO Localisation(nom_lieu) values ('Ambohitrimanjaka');
INSERT INTO Localisation(nom_lieu) values ('Ampangabe');
INSERT INTO Localisation(nom_lieu) values ('Ampanotokana');
INSERT INTO Localisation(nom_lieu) values ('Anjanadoria');
INSERT INTO Localisation(nom_lieu) values ('Anosiala');
INSERT INTO Localisation(nom_lieu) values ('Antanetibe');
INSERT INTO Localisation(nom_lieu) values ('Antehiroka');
INSERT INTO Localisation(nom_lieu) values ('Antsahafilo');
INSERT INTO Localisation(nom_lieu) values ('Avaratsena');
INSERT INTO Localisation(nom_lieu) values ('Fiadanana');
INSERT INTO Localisation(nom_lieu) values ('Iarinarivo');
INSERT INTO Localisation(nom_lieu) values ('Ivato Aeroport');
INSERT INTO Localisation(nom_lieu) values ('Ivato Firaisana');
INSERT INTO Localisation(nom_lieu) values ('Mahabo');
INSERT INTO Localisation(nom_lieu) values ('Mahereza');
INSERT INTO Localisation(nom_lieu) values ('Mahitsy');
INSERT INTO Localisation(nom_lieu) values ('Mananjara');
INSERT INTO Localisation(nom_lieu) values ('Manjakavaradrano');
INSERT INTO Localisation(nom_lieu) values ('Merimandroso');
INSERT INTO Localisation(nom_lieu) values ('Talatamaty');
INSERT INTO Localisation(nom_lieu) values ('Alakamisy');
INSERT INTO Localisation(nom_lieu) values ('Ambatomanoina');
INSERT INTO Localisation(nom_lieu) values ('Amboasary');
INSERT INTO Localisation(nom_lieu) values ('Ambohibary');
INSERT INTO Localisation(nom_lieu) values ('Ambohimanarina Marovazaha');
INSERT INTO Localisation(nom_lieu) values ('Ambohimirary');
INSERT INTO Localisation(nom_lieu) values ('Ambongamarina');
INSERT INTO Localisation(nom_lieu) values ('Amparatanjona');
INSERT INTO Localisation(nom_lieu) values ('Analaroa');
INSERT INTO Localisation(nom_lieu) values ('Anjozorobe');
INSERT INTO Localisation(nom_lieu) values ('Antanetibe');
INSERT INTO Localisation(nom_lieu) values ('Belanitra');
INSERT INTO Localisation(nom_lieu) values ('Beronono');
INSERT INTO Localisation(nom_lieu) values ('Betatao');
INSERT INTO Localisation(nom_lieu) values ('Mangamila');
INSERT INTO Localisation(nom_lieu) values ('Marotsipoy');
INSERT INTO Localisation(nom_lieu) values ('Tsarasaotra Andona');
INSERT INTO Localisation(nom_lieu) values ('Androvakely');
INSERT INTO Localisation(nom_lieu) values ('Ambohitromby');
INSERT INTO Localisation(nom_lieu) values ('Ambolotarakely');
INSERT INTO Localisation(nom_lieu) values ('Ankazobe');
INSERT INTO Localisation(nom_lieu) values ('Antakavana');
INSERT INTO Localisation(nom_lieu) values ('Antotohazo');
INSERT INTO Localisation(nom_lieu) values ('Fiadanana');
INSERT INTO Localisation(nom_lieu) values ('Fihaonana');
INSERT INTO Localisation(nom_lieu) values ('Kiangara');
INSERT INTO Localisation(nom_lieu) values ('Mahavelona');
INSERT INTO Localisation(nom_lieu) values ('Marondry');
INSERT INTO Localisation(nom_lieu) values ('Miantso');
INSERT INTO Localisation(nom_lieu) values ('Talata-Angavo');
INSERT INTO Localisation(nom_lieu) values ('Tsaramasoandro');
INSERT INTO Localisation(nom_lieu) values ('Alakamisy Fenoarivo');
INSERT INTO Localisation(nom_lieu) values ('Alatsinainy Ambazaha');
INSERT INTO Localisation(nom_lieu) values ('Ambalavao');
INSERT INTO Localisation(nom_lieu) values ('Ambatofahavalo');
INSERT INTO Localisation(nom_lieu) values ('Ambavahaditokana');
INSERT INTO Localisation(nom_lieu) values ('Ambohidrapeto');
INSERT INTO Localisation(nom_lieu) values ('Ambohijanaka');
INSERT INTO Localisation(nom_lieu) values ('Ampahitrosy');
INSERT INTO Localisation(nom_lieu) values ('Ampanefy');
INSERT INTO Localisation(nom_lieu) values ('Ampitatafika');
INSERT INTO Localisation(nom_lieu) values ('Andoharanofotsy');
INSERT INTO Localisation(nom_lieu) values ('Andranonahoatra');
INSERT INTO Localisation(nom_lieu) values ('Androhibe');
INSERT INTO Localisation(nom_lieu) values ('Ankadimanga');
INSERT INTO Localisation(nom_lieu) values ('Ankaraobato');
INSERT INTO Localisation(nom_lieu) values ('Anosizato Andrefana');
INSERT INTO Localisation(nom_lieu) values ('Antanetikely');
INSERT INTO Localisation(nom_lieu) values ('Bemasoandro');
INSERT INTO Localisation(nom_lieu) values ('Bongatsara');
INSERT INTO Localisation(nom_lieu) values ('Fenoarivo');
INSERT INTO Localisation(nom_lieu) values ('Fiombonana');
INSERT INTO Localisation(nom_lieu) values ('Itaosy');
INSERT INTO Localisation(nom_lieu) values ('Soalandy');
INSERT INTO Localisation(nom_lieu) values ('Soavina');
INSERT INTO Localisation(nom_lieu) values ('Tanjombato');
INSERT INTO Localisation(nom_lieu) values ('Tsiafahy');
INSERT INTO Localisation(nom_lieu) values ('Alasora');
INSERT INTO Localisation(nom_lieu) values ('Ambohimalaza Miray');
INSERT INTO Localisation(nom_lieu) values ('Ambohimanambola');
INSERT INTO Localisation(nom_lieu) values ('Ambohimanga Rova');
INSERT INTO Localisation(nom_lieu) values ('Ambohimangakely');
INSERT INTO Localisation(nom_lieu) values ('Anjeva Gara');
INSERT INTO Localisation(nom_lieu) values ('Ankadikely Ilafy');
INSERT INTO Localisation(nom_lieu) values ('Ankadinandriana');
INSERT INTO Localisation(nom_lieu) values ('Fieferana');
INSERT INTO Localisation(nom_lieu) values ('Manandriana');
INSERT INTO Localisation(nom_lieu) values ('Masindray');
INSERT INTO Localisation(nom_lieu) values ('Sabotsy Namehana');
INSERT INTO Localisation(nom_lieu) values ('Talata Volonondry');
INSERT INTO Localisation(nom_lieu) values ('Viliahazo');
INSERT INTO Localisation(nom_lieu) values ('Alarobia');
INSERT INTO Localisation(nom_lieu) values ('Ambanitsena');
INSERT INTO Localisation(nom_lieu) values ('Ambatolaona');
INSERT INTO Localisation(nom_lieu) values ('Ambatomanga');
INSERT INTO Localisation(nom_lieu) values ('Ambatomena');
INSERT INTO Localisation(nom_lieu) values ('Ambohibao Sud');
INSERT INTO Localisation(nom_lieu) values ('Ambohibary');
INSERT INTO Localisation(nom_lieu) values ('Ambohitrandriamanitra');
INSERT INTO Localisation(nom_lieu) values ('Ambohitrolomahitsy');
INSERT INTO Localisation(nom_lieu) values ('Ambohitrony');
INSERT INTO Localisation(nom_lieu) values ('Ambohitseheno');
INSERT INTO Localisation(nom_lieu) values ('Ampaneva');
INSERT INTO Localisation(nom_lieu) values ('Anjepy');
INSERT INTO Localisation(nom_lieu) values ('Anjoma Betoho');
INSERT INTO Localisation(nom_lieu) values ('Ankazodandy');
INSERT INTO Localisation(nom_lieu) values ('Antsahalalina');
INSERT INTO Localisation(nom_lieu) values ('Manjakandriana');
INSERT INTO Localisation(nom_lieu) values ('Mantasoa');
INSERT INTO Localisation(nom_lieu) values ('Merikanjaka');
INSERT INTO Localisation(nom_lieu) values ('Miadanandriana');
INSERT INTO Localisation(nom_lieu) values ('Nandihizana Carion');
INSERT INTO Localisation(nom_lieu) values ('Ranovao');
INSERT INTO Localisation(nom_lieu) values ('Sadabe');
INSERT INTO Localisation(nom_lieu) values ('Sambaina');
INSERT INTO Localisation(nom_lieu) values ('Soavinandriana (Ambohidratrimoanala)'); 
INSERT INTO Localisation(nom_lieu) values ('Ambatomainty Sud');
INSERT INTO Localisation(nom_lieu) values ('Ambohitromby');
INSERT INTO Localisation(nom_lieu) values ('Fenoarivo-Be');
INSERT INTO Localisation(nom_lieu) values ('Firavahana');
INSERT INTO Localisation(nom_lieu) values ('Kiranomena');
INSERT INTO Localisation(nom_lieu) values ('Mahajeby');
INSERT INTO Localisation(nom_lieu) values ('Morarano Maritampona');
INSERT INTO Localisation(nom_lieu) values ('Tsinjoarivo 22 ');
INSERT INTO Localisation(nom_lieu) values ('Ambalanirana');
INSERT INTO Localisation(nom_lieu) values ('Ambararatabe');
INSERT INTO Localisation(nom_lieu) values ('Ambatolampy');
INSERT INTO Localisation(nom_lieu) values ('Ankadinondry Sakay');
INSERT INTO Localisation(nom_lieu) values ('Ankerana Nord');
INSERT INTO Localisation(nom_lieu) values ('Anosy');
INSERT INTO Localisation(nom_lieu) values ('Belobaka');
INSERT INTO Localisation(nom_lieu) values ('Bemahatazana');
INSERT INTO Localisation(nom_lieu) values ('Bevato');
INSERT INTO Localisation(nom_lieu) values ('Fierenana');
INSERT INTO Localisation(nom_lieu) values ('Mahasolo');
INSERT INTO Localisation(nom_lieu) values ('Maroharona');
INSERT INTO Localisation(nom_lieu) values ('Maritampona');
INSERT INTO Localisation(nom_lieu) values ('Miandrarivo');
INSERT INTO Localisation(nom_lieu) values ('Soanierana');
INSERT INTO Localisation(nom_lieu) values ('Tsinjoarivo-Imanga');
INSERT INTO Localisation(nom_lieu) values ('Tsiroamandidy Fihaonana');
INSERT INTO Localisation(nom_lieu) values ('Tsiroamandidy Ville');
INSERT INTO Localisation(nom_lieu) values ('Alakamisikely');
INSERT INTO Localisation(nom_lieu) values ('Ambatomanga');
INSERT INTO Localisation(nom_lieu) values ('Ambatomirahavavy');
INSERT INTO Localisation(nom_lieu) values ('Amboanana');
INSERT INTO Localisation(nom_lieu) values ('Ambohimandry');
INSERT INTO Localisation(nom_lieu) values ('Ambohimasina');
INSERT INTO Localisation(nom_lieu) values ('Ambohipandrano');
INSERT INTO Localisation(nom_lieu) values ('Ambohitrambo');
INSERT INTO Localisation(nom_lieu) values ('Ampahimanga');
INSERT INTO Localisation(nom_lieu) values ('Andranomiely');
INSERT INTO Localisation(nom_lieu) values ('Antambolo');
INSERT INTO Localisation(nom_lieu) values ('Antenimbe');
INSERT INTO Localisation(nom_lieu) values ('Arivonimamo');
INSERT INTO Localisation(nom_lieu) values ('Arivonimamo Ii');
INSERT INTO Localisation(nom_lieu) values ('Imerintsiatosika');
INSERT INTO Localisation(nom_lieu) values ('Mahatsinjo Est');
INSERT INTO Localisation(nom_lieu) values ('Manalalondo');
INSERT INTO Localisation(nom_lieu) values ('Marofangady');
INSERT INTO Localisation(nom_lieu) values ('Miandrandra');
INSERT INTO Localisation(nom_lieu) values ('Miantsoarivo');
INSERT INTO Localisation(nom_lieu) values ('Morafeno');
INSERT INTO Localisation(nom_lieu) values ('Alatsinainikely');
INSERT INTO Localisation(nom_lieu) values ('Ambatomanjaka');
INSERT INTO Localisation(nom_lieu) values ('Analavory');
INSERT INTO Localisation(nom_lieu) values ('Andolofotsy');
INSERT INTO Localisation(nom_lieu) values ('Anosibe-Ifanja');
INSERT INTO Localisation(nom_lieu) values ('Antoby Est ');
INSERT INTO Localisation(nom_lieu) values ('Manazary');
INSERT INTO Localisation(nom_lieu) values ('Mandiavato');
INSERT INTO Localisation(nom_lieu) values ('Miarinarivo');
INSERT INTO Localisation(nom_lieu) values ('Miarinarivo II');
INSERT INTO Localisation(nom_lieu) values ('Sarobaratra');
INSERT INTO Localisation(nom_lieu) values ('Soamahamanina');
INSERT INTO Localisation(nom_lieu) values ('Soavimbazaha');
INSERT INTO Localisation(nom_lieu) values ('Zoma Bealoka');
INSERT INTO Localisation(nom_lieu) values ('Ambatoasana Centre');
INSERT INTO Localisation(nom_lieu) values ('Amberomanga');
INSERT INTO Localisation(nom_lieu) values ('Amparaky');
INSERT INTO Localisation(nom_lieu) values ('Amparibohitra');
INSERT INTO Localisation(nom_lieu) values ('Ampary');
INSERT INTO Localisation(nom_lieu) values ('Ampefy');
INSERT INTO Localisation(nom_lieu) values ('Ankaranana');
INSERT INTO Localisation(nom_lieu) values ('Ankisabe');
INSERT INTO Localisation(nom_lieu) values ('Antanetibe');
INSERT INTO Localisation(nom_lieu) values ('Dondona');
INSERT INTO Localisation(nom_lieu) values ('Mahavelona');
INSERT INTO Localisation(nom_lieu) values ('Mananasy');
INSERT INTO Localisation(nom_lieu) values ('Masindray');
INSERT INTO Localisation(nom_lieu) values ('Soavinandriana');
INSERT INTO Localisation(nom_lieu) values ('Tamponala');
INSERT INTO Localisation(nom_lieu) values ('Ambatolampy');
INSERT INTO Localisation(nom_lieu) values ('Ambatondrakalavao');
INSERT INTO Localisation(nom_lieu) values ('Ambodifarihy Fenomanana');
INSERT INTO Localisation(nom_lieu) values ('Ambohimpihaonana');
INSERT INTO Localisation(nom_lieu) values ('Andranovelona');
INSERT INTO Localisation(nom_lieu) values ('Andravola Vohipeno');
INSERT INTO Localisation(nom_lieu) values ('Andriambilany');
INSERT INTO Localisation(nom_lieu) values ('Antakasina');
INSERT INTO Localisation(nom_lieu) values ('Antanamalaza');
INSERT INTO Localisation(nom_lieu) values ('Antanimasaka');
INSERT INTO Localisation(nom_lieu) values ('Antsampandrano');
INSERT INTO Localisation(nom_lieu) values ('Behenjy');
INSERT INTO Localisation(nom_lieu) values ('Belambo Firaisana');
INSERT INTO Localisation(nom_lieu) values ('Manjakatompo');
INSERT INTO Localisation(nom_lieu) values ('Morarano');
INSERT INTO Localisation(nom_lieu) values ('Sabotsy Namotana');
INSERT INTO Localisation(nom_lieu) values ('Tsiafajavona Ankaratra');
INSERT INTO Localisation(nom_lieu) values ('Tsinjoarivo');
INSERT INTO Localisation(nom_lieu) values ('Ambatolahy');
INSERT INTO Localisation(nom_lieu) values ('Ambatomiady');
INSERT INTO Localisation(nom_lieu) values ('Ambatotsipihana');
INSERT INTO Localisation(nom_lieu) values ('Ambodiarina');
INSERT INTO Localisation(nom_lieu) values ('Ambohimandroso');
INSERT INTO Localisation(nom_lieu) values ('Ambohitompoina');
INSERT INTO Localisation(nom_lieu) values ('Ampitatafika');
INSERT INTO Localisation(nom_lieu) values ('Andranofito');
INSERT INTO Localisation(nom_lieu) values ('Antanifotsy');
INSERT INTO Localisation(nom_lieu) values ('Antsahalava');
INSERT INTO Localisation(nom_lieu) values ('Antsampandrano');
INSERT INTO Localisation(nom_lieu) values ('Belanitra');
INSERT INTO Localisation(nom_lieu) values ('CU Antsirabe'); 
INSERT INTO Localisation(nom_lieu) values ('Alakamisy');
INSERT INTO Localisation(nom_lieu) values ('Alatsinainy Ibity');
INSERT INTO Localisation(nom_lieu) values ('Ambano');
INSERT INTO Localisation(nom_lieu) values ('Ambatomena');
INSERT INTO Localisation(nom_lieu) values ('Ambohibary');
INSERT INTO Localisation(nom_lieu) values ('Ambohidranandriana');
INSERT INTO Localisation(nom_lieu) values ('Ambohimiarivo');
INSERT INTO Localisation(nom_lieu) values ('Ambohitsimanova');
INSERT INTO Localisation(nom_lieu) values ('Andranomanelatra');
INSERT INTO Localisation(nom_lieu) values ('Antanambao');
INSERT INTO Localisation(nom_lieu) values ('Antanimandry');
INSERT INTO Localisation(nom_lieu) values ('Antsoantany');
INSERT INTO Localisation(nom_lieu) values ('Belazao');
INSERT INTO Localisation(nom_lieu) values ('Mandrosohasina');
INSERT INTO Localisation(nom_lieu) values ('Mangarano');
INSERT INTO Localisation(nom_lieu) values ('Sahanivotry Manandona');
INSERT INTO Localisation(nom_lieu) values ('Soanindrariny');
INSERT INTO Localisation(nom_lieu) values ('Tsarahonenana Sahanivotry');
INSERT INTO Localisation(nom_lieu) values ('Vinanikarena');
INSERT INTO Localisation(nom_lieu) values ('Manandona ');
INSERT INTO Localisation(nom_lieu) values ('Alakamisy Anativato');
INSERT INTO Localisation(nom_lieu) values ('Alakamisy Marososona');
INSERT INTO Localisation(nom_lieu) values ('Alarobia Bemaha');
INSERT INTO Localisation(nom_lieu) values ('Ambatonikolahy');
INSERT INTO Localisation(nom_lieu) values ('Ambohimanambola');
INSERT INTO Localisation(nom_lieu) values ('Ambohimasina');
INSERT INTO Localisation(nom_lieu) values ('Andranomafana');
INSERT INTO Localisation(nom_lieu) values ('Andrembesoa');
INSERT INTO Localisation(nom_lieu) values ('Anosiarivo Manapa');
INSERT INTO Localisation(nom_lieu) values ('Antohobe');
INSERT INTO Localisation(nom_lieu) values ('Antsoso');
INSERT INTO Localisation(nom_lieu) values ('Betafo');
INSERT INTO Localisation(nom_lieu) values ('Inanantonana');
INSERT INTO Localisation(nom_lieu) values ('Mahaiza');
INSERT INTO Localisation(nom_lieu) values ('Mandritsara');
INSERT INTO Localisation(nom_lieu) values ('Manohisoa');
INSERT INTO Localisation(nom_lieu) values ('Soavina');
INSERT INTO Localisation(nom_lieu) values ('Tritriva');
INSERT INTO Localisation(nom_lieu) values ('Anjoma Ramartina');
INSERT INTO Localisation(nom_lieu) values ('Ankazomiriotra');
INSERT INTO Localisation(nom_lieu) values ('Antanambao Ambary');
INSERT INTO Localisation(nom_lieu) values ('Betsohana');
INSERT INTO Localisation(nom_lieu) values ('Fidirana');
INSERT INTO Localisation(nom_lieu) values ('Mandoto');
INSERT INTO Localisation(nom_lieu) values ('Vasiana');
INSERT INTO Localisation(nom_lieu) values ('Vinany');
INSERT INTO Localisation(nom_lieu) values ('Ambohiborona');
INSERT INTO Localisation(nom_lieu) values ('Andranomiady');
INSERT INTO Localisation(nom_lieu) values ('Antsampanimahazo');
INSERT INTO Localisation(nom_lieu) values ('Faratsiho');
INSERT INTO Localisation(nom_lieu) values ('Miandrarivo');
INSERT INTO Localisation(nom_lieu) values ('Ramainandro');
INSERT INTO Localisation(nom_lieu) values ('Valabetokana');
INSERT INTO Localisation(nom_lieu) values ('Faravohitra');
INSERT INTO Localisation(nom_lieu) values ('Vinaninony Sud'); 