INSERT INTO Reponse (id_question,intitule,id_tag) values (1,'Centre-ville',23);
INSERT INTO Reponse (id_question,intitule,id_tag) values (1,'Peripherie',24);
INSERT INTO Reponse (id_question,intitule,id_tag) values (1,'Peut importe',23);
INSERT INTO Reponse (id_question,intitule,id_tag) values (2,'Le confort',25);
INSERT INTO Reponse (id_question,intitule,id_tag) values (2,'Le luxe',26);
INSERT INTO Reponse (id_question,intitule,id_tag) values (2,'L arbordabilité',27);
INSERT INTO Reponse (id_question,intitule,id_tag) values (3,'Un appartement',28);
INSERT INTO Reponse (id_question,intitule,id_tag) values (3,'Une maison',29);
INSERT INTO Reponse (id_question,intitule,id_tag) values (3,'Une villa',30);
INSERT INTO Reponse (id_question,intitule,id_tag) values (3,'autre',null);
INSERT INTO Reponse (id_question,intitule,id_tag) values (4,'Etudiant',31);
INSERT INTO Reponse (id_question,intitule,id_tag) values (4,'Salarie',32);
INSERT INTO Reponse (id_question,intitule,id_tag) values (4,'Retraite',null);
INSERT INTO Reponse (id_question,intitule,id_tag) values (5,'Je vis seul(e)',33);
INSERT INTO Reponse (id_question,intitule,id_tag) values (5,'Je vis avec mon/ma partenaire',34);
INSERT INTO Reponse (id_question,intitule,id_tag) values (5,'Je vis avec plusieurs personnes',36);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Une pharmacie',38);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Un poste de police',39);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Une epicerie',40);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Un supermarche',41);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Un marche',42);
INSERT INTO Reponse (id_question,intitule,id_tag) values (6,'Un etablissement scolaire',43);
INSERT INTO Reponse (id_question,intitule,id_tag) values (7,'Premier plan, pour sortir plus vite',46);
INSERT INTO Reponse (id_question,intitule,id_tag) values (7,'Second plan, pour etre tranquille',47);
INSERT INTO Reponse (id_question,intitule,id_tag) values (8,'Oui, c est capitale',48);
INSERT INTO Reponse (id_question,intitule,id_tag) values (8,'Non, pas forcément',null);
INSERT INTO Reponse (id_question,intitule,id_tag) values (9,'Oui, c est plus facile ainsi',49);
INSERT INTO Reponse (id_question,intitule,id_tag) values (9,'Non, je prefere mes meubles a moi !',null);